--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 14.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: tbl_movimentacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_movimentacao (
    id bigint NOT NULL,
    data_entrada character varying(255),
    data_saida character varying(255),
    modelo character varying(30) NOT NULL,
    placa character varying(8) NOT NULL,
    tempo character varying(255),
    valor_pago double precision NOT NULL
);


--
-- Name: tbl_movimentacao_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbl_movimentacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_movimentacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_usuario (
    id integer NOT NULL,
    nome character varying(255) NOT NULL,
    senha character varying(255) NOT NULL,
    usu character varying(255) NOT NULL
);


--
-- Name: tbl_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tbl_usuario_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tbl_usuario_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tbl_usuario_id_seq OWNED BY public.tbl_usuario.id;


--
-- Name: tbl_valor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_valor (
    id bigint NOT NULL,
    valor_demais_horas double precision NOT NULL,
    valor_primeira_hora double precision NOT NULL
);


--
-- Name: tbl_valor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbl_valor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_valor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_usuario id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_usuario ALTER COLUMN id SET DEFAULT nextval('public.tbl_usuario_id_seq'::regclass);


--
-- Name: tbl_movimentacao tbl_movimentacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_movimentacao
    ADD CONSTRAINT tbl_movimentacao_pkey PRIMARY KEY (id);


--
-- Name: tbl_usuario tbl_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_usuario
    ADD CONSTRAINT tbl_usuario_pkey PRIMARY KEY (id);


--
-- Name: tbl_valor tbl_valor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_valor
    ADD CONSTRAINT tbl_valor_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

